services:
  backend:
    image: trainingf # image personalizada criada no meu docker local...
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./static:/app/static
      - ./templates:/app/templates
    restart: always
    networks:
      - dockercompose

networks: # o docker cria como padrão uma rede bridge
  dockercompose: